version: "3"
services:
    etcd:
        image: quay.io/coreos/etcd:v3.3
        volumes:
            - "etcd_data:/default.etcd"
        environment:
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    app:
        image: coredns/coredns
        command:
        - -conf
        - /Corefile
        ports:
            - "1053:53/udp"
        volumes:
            - "./Corefile:/Corefile"
volumes:
    etcd_data:
